import Joi from "joi";

export const structure = [
  {
    name: "firstName",
    type: "text",
    label: "firstName",
    required: true,
    block: false,
  },
  {
    name: "lastName",
    type: "text",
    label: "lastName",
    required: true,
    block: false,
  },
  {
    name: "companyName",
    type: "text",
    label: "companyName",
    required: true,
    block: true,
  },
  {
    name: "email",
    type: "email",
    label: "email",
    required: true,
    block: false,
  },
  {
    name: "phone",
    type: "tel",
    label: "phone",
    required: true,
    block: false,
  },
  {
    name: "city",
    type: "text",
    label: "city",
    required: true,
    block: false,
  },
  {
    name: "street",
    type: "text",
    label: "street",
    required: true,
    block: false,
  },
  {
    name: "postalCode",
    type: "number",
    label: "postalCode",
    required: true,
    block: false,
  },
  {
    name: "otherInformation",
    type: "text",
    label: "otherInformation",
    required: true,
    block: false,
  },
];

export const pattern = new RegExp(
  "(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[$@$!#.])[A-Za-z\\d$@$!%*?&.]{8,20}"
);

export const UserManageSchema = Joi.object({
  firstName: Joi.string().required(),
  lastName: Joi.string().required(),
  companyName: Joi.string().required(),
  email: Joi.number().required(),
  phone: Joi.string().required(),
  city: Joi.string().required(),
  street: Joi.number().required(),
  postalCode: Joi.number().required(),
  otherInformation: Joi.number().required(),
});

export const usersData = [
  {
    firstName: "maxim",
    lastName: "tsvetkov",
    companyName: "abcde",
    email: "maxim@gmail.com",
    phone: "0501111111",
    city: "asdsad",
    street: "asdas",
    postalCode: "6454",
    otherInformation: "sdfhsdfhsdf",
  },

  {
    firstName: "mor",
    lastName: "sharfi",
    companyName: "edcba",
    email: "mor@gmail.com",
    phone: "0502222222",
    city: "asdfghjk",
    street: "asdfghjk",
    postalCode: "1111",
    otherInformation: "asdfghjk",
  },
  {
    firstName: "beni",
    lastName: "meni",
    companyName: "Beni M ltd",
    email: "beni@gmail.com",
    phone: "0503333333",
    city: "beniyamina",
    street: "meni",
    postalCode: "2222",
    otherInformation: "beniyaminationbeniyamination",
  },
  {
    firstName: "maxim",
    lastName: "maxim",
    companyName: "maxim",
    email: "maxim@gmail.com",
    phone: "0500000000",
    city: "maxim",
    street: "maxim",
    postalCode: "1234",
    otherInformation: "maxim",
  },
  {
    firstName: "maxim",
    lastName: "tsvetkov",
    companyName: "abcde",
    email: "maxim@gmail.com",
    phone: "0501111111",
    city: "asdsad",
    street: "asdas",
    postalCode: "6454",
    otherInformation: "sdfhsdfhsdf",
  },
  {
    firstName: "maxim",
    lastName: "tsvetkov",
    companyName: "abcde",
    email: "maxim@gmail.com",
    phone: "0501111111",
    city: "asdsad",
    street: "asdas",
    postalCode: "6454",
    otherInformation: "sdfhsdfhsdf",
  },
  {
    firstName: "maxim",
    lastName: "tsvetkov",
    companyName: "abcde",
    email: "maxim@gmail.com",
    phone: "0501111111",
    city: "asdsad",
    street: "asdas",
    postalCode: "6454",
    otherInformation: "sdfhsdfhsdf",
  },
  {
    firstName: "maxim",
    lastName: "tsvetkov",
    companyName: "abcde",
    email: "maxim@gmail.com",
    phone: "0501111111",
    city: "asdsad",
    street: "asdas",
    postalCode: "6454",
    otherInformation: "sdfhsdfhsdf",
  },
];
