export const booksData = [
  {
    name: "maxim",
    author: "tsvetkov",
    category: "",
    price: "55",
    image: "rfhdrasjsadrjuhsd",
    condition: "good",
    book_parts: "2",
    stock: "1",
    hand: "2",
    publishing_year: "2002",
    translation: "english,hebrew",
    publisher: "kineret",
    description: "sfdahaerhyarhy",
  },
  {
    name: "harry poter 3",
    author: "JK rolling",
    category: "fantasy",
    price: "89",
    image: "dfgjdfjsf",
    condition: "as new",
    book_parts: "7",
    stock: "1",
    hand: "1",
    publishing_year: "2000",
    translation: "all ",
    publisher: "best books ",
    description: "asrhadsfharsdh",
  },
  {
    name: "A Brief History of Mankind",
    author: "yuval noah harari",
    category: "science",
    price: "45",
    image: "sfgjgfjsj",
    condition: "a bit used",
    book_parts: "3",
    stock: "2",
    hand: "2",
    publishing_year: "2017",
    translation: "english, hebrew",
    publisher: "my books",
    description: "dsafhsdfhsdfh",
  },
];
